<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Подготовка данных о погоде</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Подготовка данных о погоде</h2>

<hr/>

<p>author: &ldquo;Grigory Miholap&rdquo;</p>

<h2>date: &ldquo;15/11/2015&rdquo;</h2>

<h2>об источнике данных</h2>

<p><em>источник данных</em> - <a href="http://pogoda.by/zip/index.php?Year=2015#csv">pogoda.by</a><br/>
<em>дата загрузки</em>: 15/10/2015<br/>
<em>локация</em>: данные скачаны для города Минска (см. строку в таблице по ссылке с 
параметром &ldquo;№ ВМО&rdquo; = 26850)<br/>
<em>период</em> янв2006-сен2015г<br/>
<em>описание набора файлов</em> Каждый файл содержит данные по одной метеостанции за 
месяц. Дискретность метеонаблюдений 3 часа. В файле каждая запись (одна строка) 
— это один срок метеонаблюдений. Метеопараметры в строке разделяются точкой с 
запятой. Отделение целой части числа от дробной осуществляется точкой.<br/>
<em>описание данных (по столбцам)</em>:<br/>
1. число месяца;<br/>
2. срок наблюдений [часы], UTC;<br/>
3. T - температура воздуха на высоте 2 м [Цельсия];<br/>
4. dd - направление ветра на высоте 10 м [румбы, откуда дует];<br/>
5. FF - средняя скорость ветра на высоте 10 м [м/с];<br/>
6. ww - код погоды в срок наблюдения [CL - без явлений, BR - дымка, FG - туман, 
RA - дождь SHRA - ливневый дождь, SNRA - снег с дождем, SN - снег, SHSN - 
ливневый снег, TS - гроза, DZ - морось, FZ - гололед, HL - град];<br/>
7. N - количество облаков [0 - ясно, 1 - малооблачно (1-2 балла), 3 - небольшая 
облачность (3-4), 6 - переменная (5-7 баллов), 7 - обл. с прояснениями (8-9), 9 - 
сплошная (10 баллов)];<br/>
8. vv - метеорологическая дальность видимости [км];<br/>
9. U - относительная влажность воздуха [%];<br/>
10. PPP - атмосферное давление на уровне моря [гПа].  </p>

<h2>Загрузка данных</h2>

<p>включаем нужные библиотеки</p>

<pre><code class="r">library(&quot;dplyr&quot;)
library(&quot;lubridate&quot;)
library(&quot;ggplot2&quot;)
library(&quot;lattice&quot;)
library(&quot;car&quot;)
</code></pre>

<p>Загружаем первый файл</p>

<pre><code class="r">test &lt;- read.csv(&#39;./Raw data/26850_2006-01.csv&#39;, sep = &#39;;&#39;, header = F)
head(test)
</code></pre>

<pre><code>##   V1 V2   V3    V4 V5 V6 V7 V8 V9  V10
## 1  1  0 -4.3 Южный  3 CL  3 10 84 1016
## 2  1  3 -4.7   Ю-В  3 CL  1 10 86 1017
## 3  1  6 -4.8   Ю-В  2 CL  3 10 83 1018
## 4  1  9 -3.3 Южный  3 CL  9 10 81 1020
## 5  1 12 -1.1 Южный  3 CL  6 10 72 1020
## 6  1 15 -1.5 Южный  3 CL  6 10 68 1021
</code></pre>

<p>Готовим dataframe <code>weather</code> для хранения данных из всех файлов, добавляем туда 
первый загруженный файл и добавляем 2 дополнительных столбца <code>year</code> и <code>month</code> 
для записи года и месяца наблюдений (эти данные берем из имени файла)</p>

<pre><code class="r">files &lt;- list.files(path = &quot;./Raw data/&quot;, pattern = &quot;.*csv&quot;)
weather &lt;- test
weather &lt;- weather[1,1:10]
weather &lt;- cbind(weather, &quot;year&quot;, &quot;month&quot;)
weather &lt;- weather[FALSE,]
</code></pre>

<p>Скачиваем все файлы и парсим год и месяц из имени файла</p>

<pre><code class="r">for (i in 1:length(files)) {
  tyear &lt;- gsub(pattern = &quot;([0-9]{5}_)|(-\\d{1,2}\\.csv)&quot;, x=files[i], replacement = &quot;&quot;)
  tmonth &lt;- gsub(pattern = &quot;([0-9]{5}_[0-9]{4}-(0)?)|(.csv)&quot;, x=files[i], replacement = &quot;&quot;)
  temp &lt;- read.csv(paste0(&quot;./Raw data/&quot;,files[i]), sep = &quot;;&quot;, header = F)
  temp &lt;- cbind(temp, &quot;year&quot;, &quot;month&quot;)
  temp[,11] &lt;- rep(tyear, len = nrow(temp))
  temp[,12] &lt;- rep(tmonth, len = nrow(temp))
  weather &lt;- rbind(weather,temp)
}
</code></pre>

<p>Переименовываем столбцы</p>

<pre><code class="r">names(weather) &lt;- c(&quot;day&quot;, &quot;hour&quot;, &quot;tem&quot;, &quot;windd&quot;, &quot;winds&quot;, &quot;rainy&quot;, &quot;clowdly&quot;,&quot;vv&quot;, &quot;humidity&quot;, &quot;ppp&quot;, &quot;year&quot;, &quot;month&quot;)
</code></pre>

<p>И таким образом имеем датафрейм</p>

<pre><code class="r">head(weather)
</code></pre>

<pre><code>##   day hour  tem windd winds rainy clowdly vv humidity  ppp year month
## 1   1    0 -4.3 Южный     3    CL       3 10       84 1016 2006     1
## 2   1    3 -4.7   Ю-В     3    CL       1 10       86 1017 2006     1
## 3   1    6 -4.8   Ю-В     2    CL       3 10       83 1018 2006     1
## 4   1    9 -3.3 Южный     3    CL       9 10       81 1020 2006     1
## 5   1   12 -1.1 Южный     3    CL       6 10       72 1020 2006     1
## 6   1   15 -1.5 Южный     3    CL       6 10       68 1021 2006     1
</code></pre>

<p>##Анализ пропущенных и недопустимых значений</p>

<p>функция <code>checkna</code> вычисляет количество пропущенных значений для каждого столбца.
Как видим, параметр <code>clowdly</code> имеет 545 значений NA, остальные - 4-8 NA-значений.</p>

<pre><code class="r">checkna(weather)
</code></pre>

<pre><code>##      day     hour      tem    windd    winds    rainy  clowdly       vv 
##        0        0        0        0        0        0      545        8 
## humidity      ppp     year    month 
##        4        4        0        0
</code></pre>

<p>в направлении ветра <code>windd</code> есть невалидные значения с &ldquo;?&rdquo;, также есть 4917 пустых
значений</p>

<pre><code class="r">table(weather$windd, useNA = &quot;ifany&quot;)
</code></pre>

<pre><code>## 
##           Восточный  Западный       С-В       С-З  Северный       Ю-В 
##      4917      1814      3241      2519      3870      1629      3070 
##       Ю-З     Южный        ?-      ????   ???????  ???????? 
##      3865      3344       104         7        55        11
</code></pre>

<p>значения с &ldquo;?&rdquo; заменим на NA</p>

<pre><code class="r">is.na(weather$windd[grepl(&quot;\\?&quot;, weather$windd)]) &lt;- T
</code></pre>

<p>зададим уровни фактора для <code>windd</code> (и сделаем упорядоченным для дальн.
группировки), все значения вне уровней получат значение NA (в том числе 4917 
пустых значений)</p>

<pre><code class="r">weather$windd &lt;- factor(x = weather$windd, levels = c(&quot;Восточный&quot;, &quot;Западный&quot;, 
                &quot;С-В&quot;, &quot;С-З&quot;, &quot;Северный&quot;, &quot;Ю-В&quot;, &quot;Ю-З&quot;, &quot;Южный&quot;),ordered = T)
</code></pre>

<p>В параметре скорость ветра <code>winds</code> есть недопустимые значения. </p>

<pre><code class="r">table(weather$winds)
</code></pre>

<pre><code>## 
##     1     2     3     4     5 Штиль     6     7    21     8          99 
##  9151  8206  4235  1487   329  4903    79     7     1     2     1     1 
##    60    57    30    11   ???     9 
##     1     1     1     1    39     1
</code></pre>

<p>&ldquo;Штиль&rdquo; - заменим на 0, зн-я выше 21 (их всего 7) заменим на NA, значения &ldquo;???&rdquo; 
(39 шт) заменим на NA</p>

<pre><code class="r">weather$winds &lt;- as.character(weather$winds)
weather$winds[grepl(&quot;Штиль&quot;, weather$winds)] &lt;- &quot;0&quot;
is.na(weather$winds[grepl(&quot;\\?&quot;, weather$winds)]) &lt;- T
is.na(weather$winds[weather$winds %in% c(&quot;21&quot;, &quot;30&quot;, &quot;57&quot;, &quot;60&quot;, &quot;99&quot;)]) &lt;- T
</code></pre>

<p>И преобразуем <code>winds</code> в числовой формат</p>

<pre><code class="r">weather$winds &lt;- as.numeric(weather$winds)
</code></pre>

<p>В значениях влажности воздуха <code>humidity</code> есть выбросы</p>

<pre><code class="r">head(weather$humidity[order(weather$humidity, decreasing = T)], n = 20)
</code></pre>

<pre><code>##  [1] 680 174 155 148 144 136 135 133 131 127 120 119 117 115 113 110 107
## [18] 107 106 105
</code></pre>

<p>значение равное 680 заменим на NA, другие значения большие 100 заменим на 100, 
(учитывая, что отн.влажность выше 100% возможно только при специальных условиях)</p>

<pre><code class="r">is.na(weather[which(weather$humidity==680,arr.ind = T),&quot;humidity&quot;]) &lt;- T
weather$humidity[weather$humidity&gt;100] &lt;- 100
</code></pre>

<h2>Агрегирование данных</h2>

<p>Так как дискретность метеонаблюдений составляет 3 часа, то данные надо усреднить - 
группировать по параметру day+year+month
при этом рассчитаем следующие агрегированные показатели:  </p>

<ul>
<li>температура - средняя за 9,12,15,18-часовые даннные<br/></li>
<li>облачность - среднее за 9,12,15,18-часовые даннные<br/></li>
<li>скорость ветра - средняя за 9,12,15,18-часовые даннные<br/></li>
<li>направление ветра - &ldquo;максимальное&rdquo; за 9,12,15,18-часовые даннные<br/></li>
<li>влажность - средняя за 9,12,15,18-часовые даннные<br/></li>
<li>давление - среднее за 9,12,15,18-часовые даннные<br/></li>
</ul>

<pre><code class="r">t1 &lt;- subset(weather, weather$hour&gt;=9 &amp; weather$hour&lt;=18)
t2 &lt;- group_by(t1, day, month, year)
weather2 &lt;- summarise(t2, tem=mean(tem, na.rm = T), clowdly=mean(clowdly, na.rm = T), 
                      winds=mean(winds, na.rm=T), windd=max(windd, na.rm=T),
                      humidity=mean(humidity, na.rm=T), ppp=mean(ppp, na.rm=T))
</code></pre>

<p><em>замечание: было 39 предупреждений, о том, что в группах для windd не было</em> 
<em>отличных от NA значений &ldquo;no non-missing arguments to max; returning -Inf&rdquo; -</em>
<em>уточнил: это значит будут NA</em></p>

<p>проверка NA после группировки и расчета агрегированных показателей</p>

<pre><code class="r">temp &lt;- checkna(weather2)
</code></pre>

<p>хороший результат: </p>

<pre><code>##      day    month     year      tem  clowdly    winds    windd humidity 
##        0        0        0        0       11        0       39        0 
##      ppp 
##        0
</code></pre>

<h2>Добавление дополнительных параметров</h2>

<p>для облачности <code>clowdly</code> добавляем факторный вариант <code>clowdlyf</code> с 4-мя уровнями - ясно, средне, облачно, пасмурно</p>

<pre><code class="r">weather2$clowdlyf &lt;- as.character(weather2$clowdly)
weather2$clowdlyf[(weather2$clowdly&lt;=3) &amp; !is.na(weather2$clowdly)]&lt;- &#39;ясно&#39;
weather2$clowdlyf[(weather2$clowdly &gt; 3 &amp; weather2$clowdly &lt;= 7) &amp; 
                    !is.na(weather2$clowdly)]&lt;- &#39;средне&#39;
weather2$clowdlyf[(weather2$clowdly &gt; 7 &amp; weather2$clowdly &lt; 9) &amp; 
                    !is.na(weather2$clowdly)]&lt;- &#39;облачно&#39;
weather2$clowdlyf[(weather2$clowdly &gt;= 9) &amp; !is.na(weather2$clowdly)]&lt;- &#39;пасмурно&#39;
weather2$clowdlyf &lt;- factor(weather2$clowdlyf, levels = 
                              c(&quot;пасмурно&quot;, &quot;облачно&quot;, &quot;средне&quot;, &quot;ясно&quot;), ordered = T)
</code></pre>

<p>Добавляем дату (используя параметры День, Месяц, год) и удаляем столбцы День, Месяц,
Год.</p>

<pre><code class="r">weather2$date &lt;- weather2$day
for (i in 1:nrow(weather2)) {
  t1 &lt;- weather2[i,1]; if (nchar(t1)==1) {t1 &lt;- paste0(&quot;0&quot;,t1)}
  t2 &lt;- weather2[i,2]; if (nchar(t2)==1) {t2 &lt;- paste0(&quot;0&quot;,t2)} 
  weather2[i,&quot;date&quot;] &lt;- paste0(weather2[i,3],&quot;-&quot;, t2,&quot;-&quot;,t1)
}
weather2$date &lt;- as.Date(weather2$date)
weather2 &lt;- weather2[,-c(1:3)]
</code></pre>

<p>Добавляем факторную переменную сезон (зима, лето, весна, осень)</p>

<pre><code class="r">weather2$season &lt;- as.factor(season(weather2$date))
</code></pre>

<p><strong>Таким образом</strong>, данные о погоде готовы для дальнейшего анализа. Сохраняем их 
в переменную <code>weathertidy</code></p>

<pre><code class="r">dput(x = weather2, file = &quot;./weathertidy&quot;)
</code></pre>

</body>

</html>
